Extract ethogram
Imageomics/kabr-tools pull request #11
Opened 2024-07-22 21:48 UTC by zhong-al

2024-08-05 19:10 UTC, jennamk14 approved these changes

2024-08-05 19:16 UTC, egrace479 requested changes

2024-08-05 19:16 UTC, egrace479 commented on ethogram/classes.json
> +}
```suggestion
}

```

2024-08-05 19:16 UTC, egrace479 commented on ethogram/old2new.json
> +}
```suggestion
}

```

2024-08-06 03:03 UTC, dirtmaxim commented on ethogram/classes.json
> +}
Seems reasonable.

2024-08-06 03:06 UTC, dirtmaxim approved these changes

2024-08-08 16:12 UTC, egrace479 commented on ethogram/old2new.json
> +}
```suggestion
}

```

2024-08-08 16:12 UTC, egrace479 approved these changes

2024-08-08 21:12 UTC, merged