Add annotation helper script
Imageomics/kabr-tools pull request #43
Opened 2024-09-03 16:31 UTC by zhong-al

Resolves #38

2024-09-06 11:07 UTC, jennamk14 commented on README.md
suggestion: clarify miniscenes are clipped videos focused on the single individual, where the video is the raw video file. both miniscene and videos are mp4 files so this might be confusing to users.

2024-09-06 11:08 UTC, jennamk14 requested changes
suggestion: clarify miniscenes are clipped videos focused on the single individual, where the video is the raw video file. both miniscene and videos are mp4 files so this might be confusing to users.

2024-09-06 19:36 UTC, zhong-al commented on README.md
Video was added as a parameter in #42
I've updated the README.md on that PR. If that looks good, I can rebase this branch.

2024-09-26 16:24 UTC, egrace479 reviewed
One note on clarity of directions.

2024-09-26 16:24 UTC, egrace479 commented on helper_scripts/annotate_mini_scenes/README.md
> +1. Update jobs and account number in `launch_jobs.py`
```suggestion
1. Update the `jobs` and `account number` variables in `launch_jobs.py`.
```
Makes it a little clearer.

2024-09-26 17:31 UTC, egrace479 approved these changes
LGTM following other changes from earlier PRs mentioned.

2024-10-07 23:46 UTC, jennamk14 approved these changes
LGTM

2024-10-08 21:07 UTC, jennamk14 commented
@zhong-al can you resolve the conflicts and then squash & merge? Thanks!

2024-10-09 14:04 UTC, merged